# Generated by Django 2.0.6 on 2018-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
